### ISSUE TITLE
404 - boostrap.mim.css.map

### ISSUE THREAD

**Issue by mazzazzam** [murilobsd/zeus#6]
![screen shot 2016-07-06 at 10 21 15 am](https://cloud.githubusercontent.com/assets/6684836/16619486/ae65276c-4364-11e6-8cdc-6585d5affdee.png)

Arrumar caminho do boostrap.mim.css.map

**Comment by murilobsd** [comment]
Eu irei remover o flask-bootstrap e adicionarei o bootstrap direto no fonte.
